# Generated by Django 2.1.5 on 2020-01-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobitem',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='jobitem',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
